### PR TITLE
Feature/Implementation-of-platform-settings-with-AdminLTE-v3.0

### PR DESCRIPTION
**Pull request by JoharAlam**

### CODE REVIEW

**Comment by JoharAlam** [comment]
@faizan-glowlogix bhai Please Review

**Comment by faizan-glowlogix** [comment]
by default user should be able to see platform details.
[](Screenshot (4))](url)

**Comment by faizan-glowlogix** [comment]
@JoharAlam

**Comment by JoharAlam** [comment]
@faizan-glowlogix bhai functionality is added for new user to only view platform settings show page

**Pull request merged**
